@echo off
echo Starting SMK LMS Development Server...

echo [1/3] Starting Laravel server...
start "Laravel" cmd /k "php artisan serve"

echo [2/3] Starting Vite dev server...
start "Vite" cmd /k "npm run dev"

echo [3/3] Starting Queue worker...
start "Queue" cmd /k "php artisan queue:work redis"

echo All services started! Open http://localhost:8000